### ISSUE TITLE
Tooltips on a pane

### ISSUE THREAD

**Issue by timesavingbee** [freyastreamlit/streamlit-lightweight-charts#38]
Please let me know how to apply tooltips on a pane as described on the page linked below.
https://tradingview.github.io/lightweight-charts/tutorials/how_to/tooltips#floating-tooltip

**Comment by freyastreamlit** [comment]
@timesavingbee 

At present, it is not possible to achieve that due to the limitation of exposing JavaScript events, such as 'subscribeCrosshairMove', to Python.

Your request aligns with the issue described here: https://github.com/freyastreamlit/streamlit-lightweight-charts/issues/32 - I'll let you know if there are any developments.

Best,

Joe

**Comment by timesavingbee** [comment]
Thank you so much for your kind and quick reply~!

**Comment by timesavingbee** [comment]
Thank you so much for your kind and quick reply~!
And then I will get those info from issue #32.
